# Base URL
baseURL: "http://epensieve.com/"

# Ignore files
ignoreFiles:
- "\\.sh$"
- "Makefile"
- "Dockerfile"

# Default language
languageCode: "en-us"

# Basic metadata
title: "The Pensieve"
copyright: "Unless otherwise noted, all blog posts, photos, graphics, presentations and other media are published under a Creative Commons Attribution-NonCommercial (CC BY-NC) license. Unless otherwise noted, all code snippets are available under the Unlicense."
author: "Julio Novais Raffaine"
params:
  description: "Calming the Brain Storm"

# Theme configuration
theme: "syna"
#paginate: 10

# Enable all URLs to be relative, and make them end with ".html"
relativeURLs: true
#canonifyURLs: false
#uglyurls: true

# Format for posts' permalinks
#permalinks:
#  post: /:year/:month/:day/:slug

# Disable taxonomies
#disableKinds:
#- taxonomy
#- taxonomyTerm
#- section

# RSS
#rssLimit: 10
#outputFormats:
#  RSS:
#    mediatype: "application/rss"
#    baseName: "feed"

# Google Analytics
#GoogleAnalytics: "UA-72379106-1"

# Syntax highlighting
#pygmentsCodeFences: true
#pygmentsStyle: "tango"

# Privacy
#privacy:
#  youtube:
#    privacyEnhanced: true
#  twitter:
#    enableDNT: true

# Menu (Not implemented)
#menu:
#  main:
#    - name: "Home"
#      url: "/"
#    - name: "About"
#      url: "/about.html"

# Markup converters
markup:
  defaultMarkdownHandler: blackFriday
  goldmark:
    renderer:
      unsafe: true
